spring.application.name=example-for-graduate-work-main
spring.datasource.url=jdbc:postgresql://localhost:5432/avito_clone
spring.datasource.username=shopogolik
spring.datasource.password=freak
spring.jpa.hibernate.ddl-auto=update
